
# Shared by temperature and wind: each month is generated by a lag-1
# autoregression, x[k] = max(lo, c + rlag * x[k-1] + e[k] + d[k]), with
# random residuals e. d moves the mean day by day (Tmax on wet and dry
# days); without `shift`, d is 0. Every attempt draws the whole month; the
# best is kept.


# Generate the days `r` of `data`; `prev` is the value of the day before
# the month. `draw!(e)` fills e with one attempt's residuals, and
# `score(s)` rates the statistics s of an attempt (`month_stats`): 1 or
# less is a fit, which ends the search. `shift[k]`: how far day k's mean
# is from the month's (the day before the month taken as 0). Returns the
# best attempt's score.
function autoregress_month!(data, r, prev, c, rlag, draw!, score; lo=-Inf, maxrun=5_000,
                            shift=nothing)
    x = view(data, r)
    e = zeros(length(r))
    d = isnothing(shift) ? zeros(length(r)) :
        [s - rlag * (k > 1 ? shift[k-1] : 0.0) for (k, s) ∈ enumerate(shift)]
    best = zeros(length(r))
    min_err = 999_999_999.99
    found = false
    nrun = 0

    while !(min_err <= 1.0) && (nrun < maxrun)
        nrun += 1
        draw!(e)

        y = prev
        for k ∈ eachindex(e)
            y = max(lo, c + rlag * y + e[k] + d[k])
            x[k] = y
        end

        err = score(month_stats(x))
        if err < min_err
            min_err = err
            found = true
            copyto!(best, x)
        end
    end

    # keep the best attempt, not the last one
    found && copyto!(x, best)
    min_err
end


# `prev`: the day before 1 January (the previous year's 31 December), or
# `nothing` to start from January's mean. `wet`: whether each day of the
# year is wet, to make wet days `wetdry` (°C) cooler than dry days (Tmax)
function generate!(met::Met{T}; verbose::Bool=true, prev=nothing, wet=nothing,
                   wetdry=0.0) where T<:Union{Temp,Wind}
    @unpack year, obs = met

    fields = fieldnames(T)
    tgt = [getproperty(obs, f)[@m 0] for f ∈ fields]
    thd = fit_thresholds(T, tgt)

    verbose && print_start(year, tgt, thd)

    data = zeros(daysinyear(year))
    start = isnothing(prev) ? obs.mean[@m 1] : prev
    scores = map(enumerate(month_ranges(year))) do (i, r)
        p = (i == 1) ? start : data[first(r)-1]
        isnothing(wet) ? generate_month!(obs, i, data, r, p) :
                         generate_month!(obs, i, data, r, p; wet=view(wet, r), wetdry=wetdry)
    end

    s = month_stats(data)
    allok, err = check_errors(thd, tgt, [getproperty(s, f) for f ∈ fields])

    met.errors = err
    met.values = data
    met.scores = scores

    verbose && print_update(allok, met.errors)
end
